Repository meilisearch/strapi-plugin-meilisearch, pull requests merged in 2022-05, with the labels that each got.

#395 Make `filterEntry` async compatible in `filterEntries` function in `config.js`
  README.md
  server/__tests__/configuration.test.js
  server/services/meilisearch/config.js
Labels: enhancement

#400 Avoid indexing un-published entries
  server/services/meilisearch/config.js
  server/services/meilisearch/connector.js
Labels: bug

#397 Fix re-subscribing of the same content type on every addition
  server/services/lifecycle/lifecycle.js
  server/services/meilisearch/config.js
  server/services/meilisearch/connector.js
Labels: bug

#408 Add a beta release process
  .github/workflows/publish.yml
  CONTRIBUTING.md
Labels: skip-changelog

#391 Update version for the next release (v0.6.3)
  package.json
Labels: skip-changelog

#410 Fix bug component/relation fields not indexed
  server/services/lifecycle/lifecycle.js
Labels: enhancement

#421 Fetch complete entry in lifecycle
  server/services/lifecycle/lifecycle.js
Labels: skip-changelog

#420 Update strapi dependencies in playground
  playground/package.json
  playground/yarn.lock
Labels: skip-changelog, dependencies

#407 Update wording from `MeiliSearch` to `Meilisearch`
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  package.json
  resources/meilisearch-settings/make-relationship-filterable.js
  server/__tests__/configuration-validation.test.js
  server/__tests__/meilisearch.test.js
  server/configuration-validation.js
  server/services/meilisearch/client.js
  server/services/meilisearch/config.js
  server/services/meilisearch/connector.js
  server/services/store/credential.js
Labels: skip-changelog

#426 Change getContentTypeEntries to getEntries and create getEntry methods name
  server/__tests__/content-types.test.js
  server/__tests__/utils/fakes.js
  server/services/content-types/content-types.js
  server/services/meilisearch/config.js
Labels: skip-changelog

#427 Add populateEntryRule in plugin's settings
  README.md
  server/__tests__/configuration-validation.test.js
  server/configuration-validation.js
  server/services/content-types/content-types.js
  server/services/lifecycle/lifecycle.js
  server/services/meilisearch/config.js
  server/services/meilisearch/connector.js
Labels: enhancement
