Repository meilisearch/strapi-plugin-meilisearch, pull requests merged in 2022-10, with the labels that each got.

#505 Update version for the next release (v.0.7.2)
  package.json
Labels: skip-changelog

#525 Update strapi packages
  package.json
  playground/package.json
  playground/yarn.lock
  yarn.lock
Labels: skip-changelog, dependencies

#526 Add an orderby when fetching from the database
  server/__tests__/content-types.test.js
  server/services/content-types/content-types.js
Labels: bug

#528 Update version for the next release (v0.7.3)
  package.json
Labels: skip-changelog

#529 Use node 14 and not node 12 to publish package
  .github/workflows/publish.yml
Labels: bug, skip-changelog

#445 Workaround for locales
  server/services/content-types/content-types.js
Labels: enhancement

#533 Refactor validation file for readability purposes
  server/__tests__/configuration-validation.test.js
  server/configuration-validation.js
  strapi-server.js
Labels: skip-changelog

#538 Add entries query option in plugin configuration
  README.md
  resources/entries-query/locale.js
  resources/entries-query/populate.js
  resources/entries-query/publication-state.js
  server/__mocks__/meilisearch.js
  server/__tests__/configuration-validation.test.js
  server/__tests__/configuration.test.js
  server/__tests__/content-types.test.js
  server/__tests__/meilisearch.test.js
  server/__tests__/utils/fakes.js
  server/configuration-validation.js
  server/services/content-types/content-types.js
  server/services/lifecycle/lifecycle.js
  server/services/meilisearch/config.js
  server/services/meilisearch/connector.js
Labels: breaking-change

#540 Rename mocking variables
  server/__mocks__/strapi.js
  server/__tests__/configuration-validation.test.js
  server/__tests__/configuration.test.js
  server/__tests__/content-types.test.js
  server/__tests__/meilisearch.test.js
Labels: skip-changelog

#541 Update version for the next release (v0.8.0)
  package.json
Labels: skip-changelog

#543 Simplify task fetching to avoid timeout in strapi v3
  admin/src/components/Collections.js
  config/routes.json
  connectors/meilisearch/index.js
  controllers/meilisearch.js
Labels: skip-changelog, Strapi v3

#542 Make plugin v3 version compatible with latest version of Meilisearch (v0.29.1)
  README.md
  admin/src/components/Collections.js
  config/routes.json
  connectors/meilisearch/index.js
  controllers/meilisearch.js
  cypress/integration/ui_spec.js
  package.json
  yarn.lock
Labels: enhancement, Strapi v3

#548 Pass strapi client agent to meilisearch-js
  connectors/meilisearch/client.js
Labels: skip-changelog, Strapi v3

#544 Update outdated docker run commands
  CONTRIBUTING.md
  README.md
  resources/docker/docker-compose.yaml
Labels: skip-changelog, Strapi v3

#549 Update contributing guide for plugin Strapi v3 release
  .github/workflows/publish.yml
  .gitignore
  CONTRIBUTING.md
  package.json
Labels: skip-changelog, Strapi v3

#550 Fix check release script replacing tr with cut
  .github/scripts/check-release.sh
Labels: skip-changelog, Strapi v3

#554 Remove sensitive fields before transforming entries
  server/services/meilisearch/connector.js
Labels: bug

#560 Update to latest strapi version in the disclaimer in the README
  README.md
Labels: documentation
