Repository meilisearch/strapi-plugin-meilisearch, pull requests merged in 2023-09, with the labels that each got.

#806 Update dependabot.yml from ignore to allow rule
  .github/dependabot.yml
Labels: skip-changelog

#807 Remove node 14 CI tests in favor of node 18
  .github/workflows/beta-tests.yml
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  bors.toml
  playground/package.json
Labels: enhancement

#818 fix: getIndexes limited to 20 indexes
  server/__mocks__/meilisearch.js
  server/__tests__/meilisearch.test.js
  server/bootstrap.js
  server/services/meilisearch/connector.js
Labels: bug
